Fix GoalSelector crash
IoIxD/Cobblemounts pull request #21
Opened 2024-02-22 01:07 UTC by Neovitalism

Fixes crash caused by removing all goals - [See crash report here.](https://pastebin.com/YkKb9xhd)

Removing goals is redundant as Minecraft handles goals not being run while the entity has a passenger (Example: `WanderAroundGoal#canStart()`)

I also changed it so the player must have an empty hand, as pokemon can hold more than just cobblemon items.

I also bumped version and changed the gradle from 48GB to 2GB because that absolutely demolished my 16GB RAM PC and is not needed lmao

2024-02-26 17:55 UTC, IoIxD requested changes
The hand check, as is, is intentional. In average Minecraft survival, it's not uncommon to have a full inventory with items you can't easily throw away, and I think it's more convienent if the player can just mount the Pokemon with an item. The check for whether they have a Cobblemon item is a fair compromise in my opinion.

2024-02-26 18:16 UTC, Neovitalism commented
Could always just turn it into a config option, that change was requested of me when patching the crash

2024-02-26 18:28 UTC, IoIxD commented
Feel free to turn it into a config option then, although given that whoever asked you was the first to ask in several months of this mod being out I think that the current option should be the default.

2024-02-26 18:35 UTC, Neovitalism commented
Aye, shame on them for not asking for it directly then lol - had forked this before to make that exact change for someone months ago too

But ye, gotchu on default config option when I do get a minute

2024-03-02 02:38 UTC, VOrlando520 commented
No one has asked because not many base users are aware of the repo or github in general and getting hold of you in your help channel in the cobblemon discord is near impossible lol

2024-03-02 07:49 UTC, IoIxD commented
Fair enough.
I stopped checking the channel after most of the discussion started becoming diplicate questions that others could answer. Sort of relied on people to ping me if they had new questions.

2024-06-19 23:42 UTC, closed without merging